# Generated by Django 3.0.8 on 2020-07-27 16:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_auto_20200727_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='Fin',
            new_name='fin',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='Inicio',
            new_name='inicio',
        ),
        migrations.AddField(
            model_name='event',
            name='day',
            field=models.DateField(default=django.utils.timezone.now, help_text='Day of the event', verbose_name='Day of the event'),
            preserve_default=False,
        ),
    ]
