# Generated by Django 3.0.8 on 2020-07-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_auto_20200727_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='fin',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='inicio',
            field=models.TimeField(),
        ),
    ]
