# Generated by Django 3.0.8 on 2020-07-27 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20200727_1240'),
        ('eventos', '0005_auto_20200727_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
        migrations.AddField(
            model_name='event',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Customer'),
        ),
        migrations.AddField(
            model_name='event',
            name='producto',
            field=models.ManyToManyField(to='app.Product'),
        ),
        migrations.AlterField(
            model_name='event',
            name='day',
            field=models.DateField(),
        ),
    ]
