# Generated by Django 3.0.8 on 2020-07-27 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_auto_20200727_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='producto',
            new_name='product',
        ),
    ]
