# Generated by Django 3.0.8 on 2020-07-28 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20200727_1240'),
        ('eventos', '0007_auto_20200727_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='profesional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Profesional'),
        ),
    ]
