# Generated by Django 3.0.8 on 2020-07-31 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0012_auto_20200731_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='inicio',
            field=models.TimeField(verbose_name=datetime.time(0, 0)),
        ),
    ]
