# Generated by Django 3.0.8 on 2020-07-31 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0013_auto_20200731_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='fin',
            field=models.TimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='inicio',
            field=models.TimeField(null=True, verbose_name=datetime.time(0, 0)),
        ),
    ]
