# Generated by Django 3.0.8 on 2020-07-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='birthday',
            field=models.DateField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='sexo',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=200, null=True),
        ),
    ]
