# Generated by Django 3.0.8 on 2020-07-23 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20200723_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='profesional',
        ),
        migrations.AddField(
            model_name='order',
            name='profesional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Profesional'),
        ),
    ]
