# Generated by Django 3.0.8 on 2020-07-23 21:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20200723_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
